//States requested
export const GET_REQUEST = "GET_REQUEST_";
export const POST_REQUEST = "POST_REQUEST_";
export const PUT_REQUEST = "PUT_REQUEST_";
export const DELETE_REQUEST = "DELETE_REQUEST_";

export const SUCCESS_STATUS = "SUCCESS_STATUS_";
export const FAILED_STATUS = "FAILED_STATUS_";


export const SUCCESS_GET_REQUEST = GET_REQUEST + SUCCESS_STATUS;
export const FAILED_GET_REQUEST = GET_REQUEST + FAILED_STATUS;

export const SUCCESS_POST_REQUEST = POST_REQUEST + SUCCESS_STATUS;
export const FAILED_POST_REQUEST = POST_REQUEST + FAILED_STATUS;

export const SUCCESS_PUT_REQUEST = PUT_REQUEST + SUCCESS_STATUS;
export const FAILED_PUT_REQUEST = PUT_REQUEST + FAILED_STATUS;

export const SUCCESS_DELETE_REQUEST = DELETE_REQUEST + SUCCESS_STATUS;
export const FAILED_DELETE_REQUEST = DELETE_REQUEST + FAILED_STATUS;