const prefix = "TAGS_STATE_";

export const GET_TAGS_FROM_BACKEND_SUCCESS = prefix + "GET_FROM_BACKEND_SUCCESS";
export const GET_TAGS_FROM_BACKEND_LOADING = prefix + "GET_FROM_BACKEND_LOADING";
export const GET_TAGS_FROM_BACKEND_FAILED = prefix + "GET_FROM_BACKEND_FAILED";